### PR TITLE
 Added recipe for librosa 0.10.1

### PR DESCRIPTION
**Pull request by noelmullankuzhy**
Added recipe for librosa 0.10.1

librosa was not part of the supported recipes

[Terminal Output Librosa Build Success.txt](https://github.com/beeware/mobile-forge/files/14615204/Terminal.Output.Librosa.Build.Success.txt)

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by noelmullankuzhy** [comment]
I amm not sure whether this can be considered as build success unless all the dependencies of this library are built successfully too. Please advice.

**Comment by mhsmith** [comment]
As I said in #37, librosa is a pure-Python package, so it doesn't need a recipe. Once all of its native dependencies have been built (most notably Numba), the existing wheel on PyPI can be used directly.

**Comment by mhsmith** [comment]
No, you don't need to build librosa at all, because it has a `none-any` wheel on its [PyPI page](https://pypi.org/project/librosa/#files). But to use librosa you will need iOS wheels for any of the packages in the `install_requires` list which don't have `none-any` wheels on PyPI, and possibly some indirect requirements as well. 

Some of these requirements are already in [the BeeWare repository](https://anaconda.org/beeware/repo), such as NumPy; others already have issues on this tracker, such as SciPy (#10).

**Comment by noelmullankuzhy** [comment]
That you for the detailed explanation. My understanding about this was wrong since I am new to this project.

**Pull request closed without merging**
